version: 0.2

# This file defines the build process for AWS CodeBuild
# We are using a standard Maven image, which has Java and Maven pre-installed.
phases:
  install:
    commands:
      # Optional: Update Maven dependencies if not already cached
      - echo Installing dependencies...

  pre_build:
    commands:
      # Optional: Clean and install dependencies (can be skipped if cache is configured)
      - echo Pre-build phase complete.

  build:
    commands:
      # 1. Compile the Java source code
      # 2. Run all JUnit tests (defined in src/test/java)
      # 3. Package the application into a JAR file (defined in pom.xml)
      - echo Starting Maven package and test...
      - mvn package

  post_build:
    commands:
      - echo Build complete. Checking generated artifact.
      # Display the generated JAR file path
      - ls target/
      
# The artifact section tells CodeBuild what to upload to S3 after a successful build.
artifacts:
  files:
    # The packaged JAR file is our main build output
    - target/java-codebuild-sample-1.0-SNAPSHOT.jar
  # The base directory for artifacts is the root of the project ($CODEBUILD_SRC_DIR)
  base-directory: .

# Report test results to CodeBuild/CodePipeline console
reports:
  # This uses the Maven Surefire report generated during 'mvn package'
  junit_reports:
    files:
      - 'target/surefire-reports/TEST-*.xml'
    # Base directory for test reports
    base-directory: .
    # Use "ALWAYS" to ensure report generation status is visible even if the build succeeds.
    discard-paths: yes
    file-format: JUNITXML
